# H2 Console ?? ??
spring.h2.console.enabled=true

# DB ?? ?? ?? (??? ???? ?? ???? ??)
# ~/testdb? ??? ? ????? testdb.mv.db ??? ???? ??
spring.datasource.url=jdbc:h2:file:~/testdb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA ??? ?? ?? (??)
# create: ?? ???? ?? ?? (??? ???)
# update: ?? ???? ???? ??? ?? ?? (??? ??)
spring.jpa.hibernate.ddl-auto=update

# SQL ?? ?? (?? ??)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=your_very_long_random_string_for_mutsa_login_project_123456789