name: Java CI/CD with Gradle

on:
  push:
    branches: [ "main" ] # main 브랜치에 푸시될 때 실행하는 기능

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3 # 레포지토리 코드를 가져오는 기능

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin' # 자바 실행 환경을 설정하는 기능

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew # 빌드 스크립트에 권한을 부여하는 기능

      - name: Build with Gradle
        run: ./gradlew bootJar # 프로젝트를 빌드하여 JAR 파일을 생성하는 기능

      - name: SCP Transfer
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "build/libs/*.jar"
          target: "~/"
          strip_components: 2 # 생성된 JAR 파일을 서버로 전송하는 기능

      - name: Execute Remote SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            sudo pkill -9 java || true
            nohup java -jar ~/demo-0.0.1-SNAPSHOT.jar > ~/nohup.out 2>&1 &
            #기존 서버를 종료하고 새 버전으로 재시작하는 기능